function forma=superficie_normal()

forma=strcat(...
'           <SurfaceShape Points=\"9\">\n',...
'            <Point Selected=\"False\">\n',...
'              <Position x=\"%f\" y=\"%f\" z=\"0\" />\n',...
'              <Randomness x=\"0\" y=\"0\" z=\"0\" />\n',...
'            </Point>\n',...
'            <Point Selected=\"False\">\n',...
'              <Position x=\"%f\" y=\"%f\" z=\"0\" />\n',...
'              <Randomness x=\"0\" y=\"0\" z=\"0\" />\n',...
'            </Point>\n',...
'            <Point Selected=\"False\">\n',...
'              <Position x=\"-4.5\" y=\"0.04\" z=\"0\" />\n',...
'              <Randomness x=\"0.01\" y=\"0.01\" z=\"0\" />\n',...
'            </Point>\n',...
'            <Point Selected=\"False\">\n',...
'              <Position x=\"-2.5\" y=\"0.15\" z=\"0\" />\n',...
'              <Randomness x=\"0.01\" y=\"0.01\" z=\"0\" />\n',...
'            </Point>\n',...
'            <Point Selected=\"False\">\n',...
'              <Position x=\"0\" y=\"0.19\" z=\"0\" />\n',...
'              <Randomness x=\"0.01\" y=\"0.01\" z=\"0\" />\n',...
'            </Point>\n',...
'            <Point Selected=\"False\">\n',...
'              <Position x=\"2.5\" y=\"0.15\" z=\"0\" />\n',...
'              <Randomness x=\"0.01\" y=\"0.01\" z=\"0\" />\n',...
'            </Point>\n',...
'            <Point Selected=\"False\">\n',...
'              <Position x=\"4.5\" y=\"0.04\" z=\"0\" />\n',...
'              <Randomness x=\"0.01\" y=\"0.01\" z=\"0\" />\n',...
'            </Point>\n',...
'            <Point Selected=\"True\">\n',...
'              <Position x=\"%f\" y=\"%f\" z=\"0\" />\n',...
'              <Randomness x=\"0\" y=\"0\" z=\"0\" />\n',...
'            </Point>\n',...
'            <Point Selected=\"False\">\n',...
'              <Position x=\"%f\" y=\"%f\" z=\"0\" />\n',...
'              <Randomness x=\"0\" y=\"0\" z=\"0\" />\n',...
'            </Point>\n',...
'          </SurfaceShape>\n',...
'          <SetMaterial>True</SetMaterial>\n',...
'          <SurfaceMaterials>\n',...
'            <SurfaceMaterial MaterialPath=\"PPPack\\Materials\\%s\" Selected=\"True\">\n',...
'              <StartPoint>0</StartPoint>\n',...
'              <EndPoint>8</EndPoint>\n',...
'              <MaterialApplicationType>PerMeter</MaterialApplicationType>\n',...
'              <PerMeterCoverage>12</PerMeterCoverage>\n',...
'              <FitNeatly>True</FitNeatly>\n',...
'              <texture_coordinate>\n',...
'                <FlippedHorizontal>1</FlippedHorizontal>\n',...
'                <FlippedVertical>1</FlippedVertical>\n',...
'                <Angle>0</Angle>\n',...
'                <scale x=\"1\" y=\"1\" />\n',...
'                <offset x=\"0\" y=\"0\" />\n',...
'              </texture_coordinate>\n',...
'            </SurfaceMaterial>\n',...
'          </SurfaceMaterials>\n',...
'          <PanelLength>5</PanelLength>\n',...
'          <CloudInfluence>1</CloudInfluence>\n',...
'        </surface>\n');
